# Uncomment the next line to define a global platform for your project
# platform :ios, "8.0"
inhibit_all_warnings!

target "GaoDeMap" do
	pod 'AMap3DMap-NO-IDFA', '~> 5.2.1'		    # 高德地图SDK
	pod 'AMapNavi-NO-IDFA', '~> 5.1.0'		    # 高德导航SDK
	pod 'AMapLocation-NO-IDFA', '~> 2.4.0'		# 高德定位SDK
end
